# Generated by Django 2.2.5 on 2019-09-27 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 53, 31, 447454))),
                ('receive_date', models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 53, 31, 447472))),
                ('amount', models.FloatField(default=0.0)),
                ('send', models.BooleanField(default=False)),
                ('ongoing', models.BooleanField(default=False)),
                ('currency', models.CharField(default=None, max_length=5)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Partner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.VivaroUser')),
            ],
        ),
    ]
