# Generated by Django 2.2.5 on 2019-09-27 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receive_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 55, 36, 79277)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 55, 36, 79259)),
        ),
    ]
