# Generated by Django 2.2.5 on 2019-09-27 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(default=None, max_length=25, unique=True)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in', models.BooleanField(default=False)),
                ('logged_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VivaroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default=None, max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=200, unique=True)),
                ('password', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=100, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(unique=True)),
                ('last_date', models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 53, 31, 446819))),
                ('is_expired', models.DateTimeField(null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.UserAction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.VivaroUser')),
            ],
        ),
    ]
