# Generated by Django 2.2.5 on 2019-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VivaroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(default=None, max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=200, unique=True)),
                ('password', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=100, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('bonus', models.FloatField(default=0.0)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
            ],
        ),
    ]
