# Generated by Django 2.2.5 on 2019-09-19 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 14, 33, 50, 848631)),
        ),
    ]
