# Generated by Django 2.2.5 on 2019-09-27 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivarouser',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vivarouser',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 55, 36, 78605)),
        ),
    ]
