# Generated by Django 2.2.5 on 2019-09-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivarouser',
            name='last_name',
        ),
    ]
