# Generated by Django 2.2.5 on 2020-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200212_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
